# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59cb7824c08097f295c247987a16ad9e391b68c03cb1ac6f7f920e1b5fbe724c24d6cdded9ccd9d0767f8cb85657cb341f4a2ab53392dcfecd6242b3dc4dce7d

test:
  secret_key_base: efc4415af43c9937d32e1d21d0d7576c68cce9f241b9758fc0bf419eb23bc074da41a0dc6245f8937a86ab3b3fa1c53a6a86231ffe7603b5e98d8ebd7a4eb669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
